### ISSUE TITLE
joins in groups

### ISSUE THREAD

**Issue by sescobb27** [ankane/pgsync#100]
Hey, love this tool, we are trying to use it as a sync mechanism for an offline DB in IOT devices located in buildings, so we have a central DB and we want to have a small copy in the device so when the device's internet connection goes down, it can access that small copy and keeps working until connection goes up again.

Is not and issue but a question, each device would need a set of the data that is in the main DB (one building local DB should not have data from other building), so i would like to only sync related data via joins, i saw the example using groups with variables, but was wondering if i can reference other tables using joins or other complex query? e.g

```yml
groups:
  building:
    building: "where id = {1}"
    tower: "where building_id = {1}"
    floor: "join tower on tower.id = floor.tower_id" # join on previous tower table
    apartment: "join floor on floor.id = apartment.foor_id" # join on previous floor table
    user: "join apartment and apartment_user" # join on multiple data so i would require a complex join
    role: "all_roles"
    apartment_user: "join apartment and user"
```
