### ISSUE TITLE
Pass variable to data_rules value

### ISSUE THREAD

**Issue by robinvdvleuten** [ankane/pgsync#134]
It would be a very nice addition if you are somehow able to pass a variable to be used as a data rule to for example set a foreign key to an id already existing in the local database.

**Comment by ankane** [comment]
Hey @robinvdvleuten, not sure I completely follow. Can you share what this would look like in the config, and more about how it would work?

**Comment by robinvdvleuten** [comment]
Sure! We are using pgsync to retrieve "production" data in our local environment. As we are using `lockbox` in combination with AWS KMS, we have different keys on our environments so we can only migrate unencrypted data. 

My idea was to "blend" the unencrypted production data with local encrypted generated seeds (for example users with passwords). So I came up with this pgsync configuration;

```yaml
groups:
  account:
    accounts: "where name = '{1}'"
    account_users: "where account_id in (select id from accounts where name = '{1}') limit 1"

data_rules:
  account_users.user_id:
    value: "0037d00a-104e-4738-ad03-726870a42d61"
```

As you can see, it retrieves an account by a name passed as argument and I "connect" a local seeded user with the `accounts_users` table to grant this local user permission to access the synced account. 

But as the `account_users.user_id` value is fixed, every time someone would like to run pgsync, it needs to change the pgsync configuration. It would be nice to be able to set this value through an argument or maybe through an environment variable.
