### ISSUE TITLE
 No primary key Error

### ISSUE THREAD

**Issue by Nilanth** [ankane/pgsync#163]
When running the below command for some tables, we get **(No primary key)** error and no data is updated.

` pgsync group1  --jobs 1 `

**Comment by ankane** [comment]
Hey @Nilanth, if you have any tables that have a `where` or other SQL clause in the group, those tables need to have to primary key to use pgsync.

```yaml
groups:
  product:
    products: "where id = 123"
```
