### ISSUE TITLE
PG::ConnectionBad: connection to server at "target_postgres_ipxxx", port xxx failed: timeout expired

### ISSUE THREAD

**Issue by Auggie321** [ankane/pgsync#166]
Hi sir,

wanna sync local postgres to remote postgres;

pgsync run in docker ubuntu:18.04, also docker ubuntu18.04 installed ruby,gem, psql(as same to remote psql version)and pgsync
```
local pg and remote pg has same version, database name;
local pg has more test data(20000 tables), but remote is new one only with basic test tables(1500 tables);

root@e237b1f10be4:/# cat /etc/issue 
Ubuntu 18.04.6 LTS \n \l
root@e237b1f10be4:/# gem --version
2.7.6
root@e237b1f10be4:/# ruby --version
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
root@e237b1f10be4:/# pgsync --version
0.7.2


from docker ubuntu18 terminal, psql  postgresql://flxxxx:clxxxx@xxxx:13111/clxxxx successfully.
psql local 10.68.110.16:5432  successfully too.

root@e237b1f10be4:/# psql postgresql://flxx:clxx@xxx:13111/clxxx
psql (10.22 (Ubuntu 10.22-0ubuntu0.18.04.1), server 10.5)
Type "help" for help.

clxx=# \q
root@e237b1f10be4:/# psql postgresql://flxx:clxx@10.68.110.16:5432/clxx
psql (10.22 (Ubuntu 10.22-0ubuntu0.18.04.1), server 10.5)
Type "help" for help.

clxx=#
````
from docker ubuntu18 terminal,  executed pgsync --config=./pgsync.yml 
always found bellow issues;
```
root@e237b1f10be4:/# pgsync --config=./pgsync.yml 
From: clouddb on 10.68.110.16:5432
To: clouddb on xx.xx.xx.xx:5432
Missing tables: t_test1..,,t_test2.., tetstN...,
******
✔ t_test_acl - 0.2s
✖ t_test1_test111 (no partition of relation "t_test1_test111" found for row)
✖ t_test2_test222_hour (no partition of relation "t_test2_test222_hour" found for row)
✔ t_test2_policy - 0.2s
✔ t_test3_policy - 0.2s
✔ t_test2_test2_policy - 0.3s
✖ t_test4_5mi (no partition of relation "t_test4_5mi" found for row)
✖ t_test5_hour (no partition of relation "t_test5_hour " found for row)
✖ t_test6_hour (no partition of relation "t_test6_hour" found for row)
PG::ConnectionBad: connection to server at "xx.xx.xx.xx", port 13111 failed: timeout expired
```

```
root@e237b1f10be4:/# cat pgsync.yml 
from: postgresql://flxxx:xxx@10.68.110.16:5432/clxxx
to: postgresql://flxxxx:clxxxx@xxxx:13111/clxxxx
groups:
  group1:
    - t_*

to_safe: true
data_rules:
  email: unique_email
  phone: unique_phone
  last_name: random_letter
  birthday: random_date
  encrypted_*: null
```
is there any suggestions about it.

thanks.
