### ISSUE TITLE
Getting error :- undefined method `split' for #<Hash:0x00007fffed6024b8>

### ISSUE THREAD

**Issue by Parth909** [ankane/pgsync#201]
This is the script I have used

```yml
from: local_db_url

# destination database URL
to: remote_db_url

to_safe: true

exclude:
  - Dispatches
  - Follows
  - Labels


# define groups
groups:
  migrate_data:
    - Workspaces: "WHERE name LIKE 'FORM TEMPLATES [Don't Delete & Keep the forms open]'"
    - Forms: "WHERE \"workspaceId\" IN (SELECT id FROM Workspaces WHERE name LIKE 'FORM TEMPLATES [Don't Delete & Keep the forms open]')"

```

And this is the command I have ran `pgsync migrate_data`

Output :- 
```
undefined method `split' for #<Hash:0x00007fffed6024b8>
```
