### ISSUE TITLE
Question: `statement` executes once and applied to all rows on a table?

### ISSUE THREAD

**Issue by NominalTrajectory** [ankane/pgsync#213]
Hi, 

I'm using this project in combination with https://gitlab.com/dalibo/postgresql_anonymizer

And I have this in my `.pgsync.yml`:

```yaml
data_rules:
  # Sanitize Bank Accounts
  bank_accounts.iban:
    statement: "(SELECT anon.fake_iban() AS iban)"
```

What I see in the end is that the same output is applied to all rows:

![image](https://github.com/ankane/pgsync/assets/47399749/4aef817a-4be2-421f-b3c3-30fbe1d08067)

---

Is it possible to make the statement execute for each row?
