### ISSUE TITLE
How to use docker to run pgsync?

### ISSUE THREAD

**Issue by tankxxl** [ankane/pgsync#218]
<img width="873" alt="image" src="https://github.com/ankane/pgsync/assets/1826540/56502153-fb9b-45cf-8986-781ed327a57f">
How to pass yml file to docker command?

**Comment by zhangcheng** [comment]
See if https://github.com/ankane/pgsync/issues/198#issue-1901324389 helps

**Comment by magixus** [comment]
someone can use `docker compose` with the following `docker-compose.yml`
```docker-compose
services:
  pgsync:
    image: ankane/pgsync
    container_name: pgsync
    volumes:
      - ./pgsync.yml:/opt/.pgsync.yml
    working_dir: /opt
    command:
      "--schemas public --no-sequences --preserve"
```

and `./pgsync.yml`
```yaml
from: <connection string source>
to: <connection string target>
to_safe: true # just in case
```

you can then do: 

```bash
docker compose run pgsync --debug # or --list or any other additional commands 

```
