### ISSUE TITLE
Conditional Data Rules

### ISSUE THREAD

**Issue by onwardmk** [ankane/pgsync#228]
Is there a way to conditionally anonymize data?

In most cases, I want to do this:
```yml
data_rules:
  users.email: unique_email
  users.last_name:
    statement: "random_last_name()"
  users.encrypted_password:
    value: "$2a$10$EknBYSZS0IkaL6ilYmB9S.6lQCYn.KVY1VsDgMes2ghrcY3ZKvETO"
  users.phone: unique_phone
  users.phone_normalized: unique_phone
```

Except for `users` where the `email` ends in "@somedomain.com." Is this possible?

**Comment by ankane** [comment]
Hi @onwardmk, you can use `statement` for this:

```yml
data_rules:
  email:
    statement: "CASE WHEN email LIKE '%@somedomain.com' THEN email ELSE 'email' || id || '@example.org' END"
```
