### ISSUE TITLE
--disable-user-trigger options results in "cannot ALTER TABLE 'some_table' because it has pending trigger events"

### ISSUE THREAD

**Issue by onwardmk** [ankane/pgsync#230]
I'm seeing the same issue described in #200 when I run this command:
```sh
pgsync --config pgsync.yml --defer-constraints --disable-user-triggers
```

```yml
# pgsync.yml
from: postgres://<db connection string>?sslmode=require&connect_timeout=60
to: postgres://user@localhost:5432/my_db

exclude:
  - ar_internal_metadata
  - schema_migrations
  - excluded_table1
  - excluded_table2

schemas:
  - public
```

When pgsync attempts to copy the first table with a trigger, I see something like this:
```sh
✖ some_table (cannot ALTER TABLE "some_table" because it has pending trigger events)
```

Then the copy for every following table looks like this:
```sh
✖ another_table (current transaction is aborted, commands ignored until end of transaction block)
```

Until the sync ends with this:
```sh
ERROR:  current transaction is aborted, commands ignored until end of transaction block
```

The triggers are for auditing and look something like this:
```sql
CREATE TRIGGER some_table_audit_trigger 
AFTER INSERT OR DELETE OR UPDATE 
ON public.some_table 
FOR EACH ROW EXECUTE FUNCTION audit_trigger_function()
;
```

The function looks like this:
```sql
CREATE OR REPLACE FUNCTION public.audit_trigger_function()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
  DECLARE
    audit_id BIGINT := NEXTVAL('audit_id_seq');
    audit_diff JSONB := NULL;
    audit_request_context JSONB := CONNECTION_CONTEXT_JSON('request_context');
    audit_table TEXT := QUOTE_IDENT(TG_TABLE_NAME || '_audit');
    audit_sql TEXT := 'INSERT INTO ' || audit_table || ' SELECT $1, $2, NOW(), $3, $4, $5.*';
  BEGIN
    IF (TG_OP = 'INSERT') THEN
      EXECUTE audit_sql USING audit_id, 'I', audit_diff, audit_request_context, NEW;
    ELSIF (TG_OP = 'UPDATE') THEN
      audit_diff := (ROW_TO_JSON(OLD.*)::JSONB @<> ROW_TO_JSON(NEW.*)::JSONB) - '{updated_at}'::TEXT[];
      EXECUTE audit_sql USING audit_id, 'U', audit_diff, audit_request_context, NEW;
    ELSIF (TG_OP = 'DELETE') THEN
      EXECUTE audit_sql USING audit_id, 'D', audit_diff, audit_request_context, OLD;
    END IF;

    RETURN NULL;
  END;
$function$
```

postgresql version: 15.7
pgsync version: 0.7.4
