### ISSUE TITLE
Statement Interpolation with Replacements

### ISSUE THREAD

**Issue by onwardmk** [ankane/pgsync#232]
Is there a way to use replacements with a `statement`. I'd like to do something like this:

```yaml
data_rules:
  email:
    statement: "CASE WHEN email LIKE '%@somedomain.com' THEN email ELSE unique_email END"
```
