### ISSUE TITLE
Question: how to properly apply data rules to JSONB columns?

### ISSUE THREAD

**Issue by alexanderadam** [ankane/pgsync#242]
I tried

```yaml
data_rules:
  models.json_b_column:
    value: "'{}'::jsonb"
```

But this value isn't working. 🤔
