### ISSUE TITLE
Passing mutiple ids for groups

### ISSUE THREAD

**Issue by ogerman** [ankane/pgsync#8]
Hello, I'm trying to pass multiple ids to one group with no luck

`pgsync product:(1,2,3)`

```
groups:
  product:
    products: "where id IN {1}"
    reviews: "where product_id IN {1}"
    coupons: "where product_id IN {1} order by created_at desc limit 10"
    stores: "where id in (select store_id from products where id IN {1})"
```
